### ISSUE TITLE
Mutiple Area Unit

### ISSUE THREAD

**Issue by nok5150** [etewiah/property_web_builder#105]
Your project is brilliant and I going to try it for my website but just a little bit sticky.   Could you supply for editable or more area unit?  Or how do I append them more?  Because in Thailand their use local metric in selling house.  Thank you.

**Comment by nok5150** [comment]
And do you plan for Rent property?  Or pls, guide me how to customize that.  Thanks again.

**Comment by etewiah** [comment]
Hello @nok5150 , if you look at the demo you will see that it supports rental properties:

https://propertywebbuilder.herokuapp.com/en/rent
