### ISSUE TITLE
Default Area Unit

### ISSUE THREAD

**Issue by nok5150** [etewiah/property_web_builder#107]
Thanks for your last reply.  The remain question is How do I create more  Area Unit?  Here in SEA we use vary of area unit beside SI and BI metric.  Also floating Plot and Construction area. in 2 decimal.

**Comment by etewiah** [comment]
Sorry about the delay.   To add more Area Units you would have to be a developer who is comfortable going through the source code to make the changes.  Unfortunately at the moment I'm too busy to be able to help with this.
