### ISSUE TITLE
Project communication channels

### ISSUE THREAD

**Issue by ciroiriarte** [etewiah/property_web_builder#112]
Hello!, I don't have issues to raise so far but I have many questions :).

I'm evaluating building a small web site with real state offerings, and I'm struggling to find where can I ask questions other users can answer. Is there any forum/IRC channel/discord server related to the project?

**Comment by etewiah** [comment]
Hi  @ciroiriarte , I haven't got round to setting up a forum yet but feel free to ask your questions here.
