### ISSUE TITLE
Problem Deploying app to Heroku

### ISSUE THREAD

**Issue by ck7798** [etewiah/property_web_builder#117]
Hi everyone! I am a bit new to using ruby on rails as well as Heroku. 
I'm having an issue when I click deploy app to Heroku, this is the error: 
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Ruby app detected
-----> Installing bundler 2.2.16
-----> Removing BUNDLED WITH version in the Gemfile.lock
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.6.6
-----> Installing dependencies using bundler 2.2.16
       Running: BUNDLE_WITHOUT='development:test' BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
       Fetching gem metadata from https://rubygems.org/............
       Your bundle is locked to mimemagic (0.3.5) from rubygems repository
       https://rubygems.org/ or installed locally, but that version can no longer be
       found in that source. That means the author of mimemagic (0.3.5) has removed it.
       You'll need to update your bundle to a version other than mimemagic (0.3.5) that
       hasn't been removed in order to install.
       Bundler Output: Fetching gem metadata from https://rubygems.org/............
       Your bundle is locked to mimemagic (0.3.5) from rubygems repository
       https://rubygems.org/ or installed locally, but that version can no longer be
       found in that source. That means the author of mimemagic (0.3.5) has removed it.
       You'll need to update your bundle to a version other than mimemagic (0.3.5) that
       hasn't been removed in order to install.
 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

The same error appears when trying to deploy as a standalone site like shown in this image below:
![pwb error](https://user-images.githubusercontent.com/75861250/121950842-d04b0a80-cd62-11eb-8d1c-8e1c535ccb0b.png)

Could someone kindly help me and advise a way forward. Thanks.

**Comment by etewiah** [comment]
Looks like the issue with mimemagic dependency:

https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1

I won't be able to fix it this week but I'll try to get to it next week.

**Comment by ck7798** [comment]
> Looks like the issue with mimemagic dependency:
> 
> https://dev.to/cseeman/what-s-up-with-mimemagic-breaking-everything-he1
> 
> I won't be able to fix it this week but I'll try to get to it next week.

Any luck with it?

**Comment by etewiah** [comment]
Hi @ck7798 , I've updated the pwb-heroku package to use the updated mimemagic gem.  Deploying should work now.

Also if you want to try the Saas version of PropertyWebBuilder, reach out to me and I'll deploy an instance for you to try out.

**Comment by ck7798** [comment]
thanks a lot @etewiah, I'm getting a problem when building the app where it says 'Could not detect the rake tasks'

**Comment by etewiah** [comment]
Okay, looks like carrierwave needed to be updated too - should work now.

**Comment by ck7798** [comment]
Yes it works well now, thank you very much!
