### ISSUE TITLE
Adding currency

### ISSUE THREAD

**Issue by ck7798** [etewiah/property_web_builder#118]
I would like to add the Kenya shilling to the currency as well as Swahili language. I'm also having a problem saving data from the request and contact forms. Any advice on what to do?

**Comment by etewiah** [comment]
Hi there,

To add support for another region you can follow this guide:

 https://github.com/etewiah/property_web_builder/wiki/Adding-translations-for-a-new-language

For the forms you can follow this.
https://github.com/etewiah/property_web_builder/wiki/Enabling-contact-forms

If you come across any issues in the future please remember to open an issue for each individual problem you encounter and some detailed information about exactly the problem you encountered (error logs, ruby version etc etc).
