### ISSUE TITLE
How to edit code for the Heroku deloyed app

### ISSUE THREAD

**Issue by ck7798** [etewiah/property_web_builder#119]
Hello, I am having trouble opening the code locally on my pc from the deployed app on heroku. I have already installed the heroku CLI and git but I'm still facing this issue. Any suggestions on how to go about this would be of great help. Thanks.

**Comment by etewiah** [comment]
Sorry I have no idea what you mean.

**Comment by ck7798** [comment]
Ok, let me try be clearer. I'm new to ruby on rails and managed to successfully deploy pwb on heroku. I have already made some changes to the app deployed via the admin page. Now my problem is I would like to edit the code itself for things like the currency and etc. and don't really know how to.
