### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by edwood007** [etewiah/property_web_builder#12]
Hello, : )
I've installed Wordpress, Joomla etc but how do you install this?  I've uploaded to my server etc ..
Thanks,
Ed

**Comment by etewiah** [comment]
In the README I explain that you can deploy just by clicking this button:

[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://heroku.com/deploy?template=https://github.com/etewiah/pwb-for-heroku)

Or by following these instructions:

Install into an existing Rails project by adding these lines in your applications's Gemfile:

```ruby
gem 'pwb', git: 'https://github.com/etewiah/property_web_builder', branch: 'master'
gem 'globalize', git: 'https://github.com/globalize/globalize'

```

Also, be sure to use Postgres as your database (by having the "pg" gem and Postgres installed locally 
And then execute:
```bash
$ bundle
```

Mount the PropertyWebBuilder by adding the following to your routes.rb file:
```ruby
mount Pwb::Engine => '/'
```

and run the ff commands from the console:
```bash
rails pwb:install:migrations
rails db:create
rails db:migrate
rails pwb:db:seed
```
