### ISSUE TITLE
Error deploy to heroku

### ISSUE THREAD

**Issue by Viniciusvalenca** [etewiah/property_web_builder#128]
when i tried to deploy on heroku i got this error

`rake aborted!
ArgumentError: wrong number of arguments (given 3, expected 2)
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/type/adapter_specific_registry.rb:9:in `add_modifier'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/type.rb:27:in `add_modifier'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:842:in `<class:PostgreSQLAdapter>'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:80:in `<module:ConnectionAdapters>'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:52:in `<module:ActiveRecord>'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/postgresql_adapter.rb:30:in `<top (required)>'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/connection_specification.rb:191:in `spec'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:975:in `establish_connection'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/connection_handling.rb:60:in `establish_connection'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/railtie.rb:136:in `block (2 levels) in <class:Railtie>'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:71:in `instance_eval'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:43:in `block in on_load'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:42:in `each'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/lazy_load_hooks.rb:42:in `on_load'
/app/vendor/bundle/ruby/3.0.0/gems/activerecord-5.2.6/lib/active_record/railtie.rb:132:in `block in <class:Railtie>'
/app/vendor/bundle/ruby/3.0.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
/app/vendor/bundle/ruby/3.0.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
/app/vendor/bundle/ruby/3.0.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/app/vendor/bundle/ruby/3.0.0/gems/railties-5.2.6/lib/rails/initializable.rb:60:in `run_initializers'
/app/vendor/bundle/ruby/3.0.0/gems/railties-5.2.6/lib/rails/application.rb:361:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `block in require'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
/app/vendor/bundle/ruby/3.0.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:291:in `require'
/app/vendor/bundle/ruby/3.0.0/gems/railties-5.2.6/lib/rails/application.rb:337:in `require_environment!'
/app/vendor/bundle/ruby/3.0.0/gems/railties-5.2.6/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/app/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `load'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:58:in `kernel_load'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/cli/exec.rb:23:in `run'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/cli.rb:483:in `exec'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/cli.rb:31:in `dispatch'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/cli.rb:25:in `start'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/exe/bundle:48:in `block in <top (required)>'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/app/vendor/bundle/ruby/3.0.0/gems/bundler-2.3.10/exe/bundle:36:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)`

**Comment by etewiah** [comment]
Hi @Viniciusvalenca , I haven't had the chance to test with ruby 3.  I will update the readme with this.

**Comment by etewiah** [comment]
Hi @Viniciusvalenca, I have now updated the project to use Rails 6 so Ruby 3 is now supported.

I have also changed it from a Rails engine to a standalone project.  Please try it out and let me know how it goes.

**Comment by phelix001** [comment]
![image](https://user-images.githubusercontent.com/5187100/217808186-56116380-7d1e-4b25-9da6-f03d920b0af5.png)


heroku plan is discontinued, using one click install from gitsite.

**Comment by etewiah** [comment]
Hi @phelix001 , the free heroku plan is indeed no longer available.
