### ISSUE TITLE
Password Reset Error..

### ISSUE THREAD

**Issue by calebyk** [etewiah/property_web_builder#15]
I am trying to reset my password, but I have got this error message..

Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

**Comment by etewiah** [comment]
Hi @calebyk ,
I had the chance to investigate this today.  I could not reproduce the error you mentioned.  I suspect you might have made some changes to some links and that has caused the error.  Can you let me know if you changed anything?

There was a problem though with getting redirected to a non-existing page after changing the password.  I think it is unrelated but you can try updating just to check.

I have also deployed a test app here so you can verify that it works.  I changed the password for admin@example.com to pwb111111 without any problems.  You can try changing it again to confirm.

https://pwbtest.herokuapp.com/

**Comment by calebyk** [comment]
-- 
                          \\\\\lll///////
                           ( (o) (o))
**==oOOO=======(_)=====OOOo=========**
                        Caleb Y. Kang
 "Resourceful Center with more than Conquerors"
               "300 CEOs! 300 STAFFs!"
                *"Builder's Life"*
               (Cell) 212-677-2451
               (From Korea) 070-8278-8973
**=================Oooo==============**
                         oooO    (   )
                          (   )       ) /
                           \ (       (_/
                            \_)

**Comment by etewiah** [comment]
Hi @calebyk, any update on this?  If I don't hear back from you shortly I will close this ticket as I cannot reproduce the error you mention.

**Comment by calebyk** [comment]
Thank you,

It is done well..
Thank you.. again..

**Comment by etewiah** [comment]
Great - happy to hear that.  Any other issues, feel free to let me know.

**Comment by deepcell** [comment]
Hi, how can I change admin password? 
the table structure has a column called `encrypted_password` data type `character varying`, what is the correct way to generate this password? I can do myself, I just need to know which algorithm was used and where it is located. 
Thanks, by the way, very nice App. If I can contribute somehow I will.

**Comment by deepcell** [comment]
Please ignore my comment above, it's working now. Thanks.
