### ISSUE TITLE
Admin menu should collapse after selection

### ISSUE THREAD

**Issue by mmikeww** [etewiah/property_web_builder#16]
I'm just testing out the demo site. When you click on the 3 lines to open up the menu on the left, after selecting an item from the menu, the menu remains open. I think it should collapse back in

**Comment by etewiah** [comment]
Thanks for pointing that out.  

I believe you mean in the admin menu on a small screen right?  I just had a look and you are right - it does not collapse back after an item is selected.

I will look into it as soon as I get the chance.

**Comment by mmikeww** [comment]
Ah yes, my browser window wasn't full sized. I now see that by default that menu is always visible with larger sized screens

**Comment by etewiah** [comment]
Still a bug ;) 

I'll look into it.

**Comment by etewiah** [comment]
Fixed in latest update
