### ISSUE TITLE
Measurement unit isn't updated in admin panel

### ISSUE THREAD

**Issue by mmikeww** [etewiah/property_web_builder#17]
1. Change a property from square meters to sq feet.
2. Save
3. The top summary part in the admin panel does not get updated 

http://imgur.com/a/NyjhA

**Comment by etewiah** [comment]
You're great at spotting the details - really appreciate that.   

It will only take a few minutes to fix this and the other issue you raised but I'm busy with some major improvements to the content management side of things so won't be able to do it right away.  Will update this issue as soon as I get the chance to fix it.

**Comment by mmikeww** [comment]
No worries man. I'd try to fix them myself but I'm not a ruby dev. I got the thing running on heroku but can't figure out how to deploy updates from github to heroku. Still learning

**Comment by etewiah** [comment]
On the heroku dashboard for your app, there is a deploy page.  In there you will see a section that allows you to "deploy a github branch".  If you set that up and click the button it will do an update.
If you encounter any problems with that just let me know.

**Comment by mmikeww** [comment]
Yeah I'm working on it. It failed using the 'property_web_builder' repo, gonna try next with the 'pwb_for_heroku' repo. I guess I'd need to change some Gemfiles in there to point to my copy of it though?

**Comment by etewiah** [comment]
Yeah, you want the pwb_for_heroku repo.  Should work without any changes.  
For major updates ( where db migrations need to be run for example ) you may need to use the heroku console.  We can discuss that later when needed.

**Comment by mmikeww** [comment]
Yeah but so if I make a fix in my fork, then to test it I should change the Gemfile and Gemfile.lock within the `pwb_for_heroku` repo to point to my fork?

**Comment by etewiah** [comment]
If you are deploying your own fork, don't use the "Deploy to Heroku" button - that is coded to use the main "pwb_for_heroku" repo.
To deploy your own fork you need to follow the standard procedure for a heroku deploy.
If any of that is not clear please open a separate issue as this current issue is for something else ;)

**Comment by etewiah** [comment]
Hi @mmikeww, hope deploying updates to heroku worked for you.  The original issue raised here has been resolved so I'm going to close this.

**Comment by mmikeww** [comment]
Its impossible to view the diff because of the minified javascript... perhaps the code in the repo should be saved in readable form and then minified during the build/deploy?

**Comment by mmikeww** [comment]
I ask, because I'm not seeing the fixes when I depoy to heroku, and I'm having a hard time inspecting the diff

**Comment by etewiah** [comment]
Yes, it's not possible to figure out the javascript for the admin panel right now.  I aim to restructure the code soon to include a readable form  of it in the main project.
For now you'll just have to trust me that it's fixed ;)   If you look at this for example, you can see that any changes to the measurement unit are reflected in the top summary part right away.

**Comment by mmikeww** [comment]
Sorry I'm new to heroku... I hadn't updated the gemfile in the pwb-for-heroku repository and that's why I wasn't seeing the changes!

**Comment by etewiah** [comment]
Ah cool, glad you got it working ;)
