### ISSUE TITLE
Change of navigation properties don't save

### ISSUE THREAD

**Issue by cvillalba** [etewiah/property_web_builder#19]
Hi Ed

I have updated pwb gem and after deploy in heroku, I notice that there was no menu next to the ADMIN button.
I check the administration screen and notice the navigation configuration section, but after change the configuration to show some options, changes don save, so now the website has no menu displaying.

Do you have any idea what can be wrong ?

Thanks again.

PS: Great improvements in the update by the way. Thanks

**Comment by etewiah** [comment]
Hi Carlos, thanks for checking out the latest update.  Do you get any errors in the admin panel when you try to save changes to the navigation? If you open up the javascript console in chrome you might find more info.

Also you might want to run this command in the console to delete all the navigation items:

`Pwb::Section.destroy_all`

And then run this to recreate them from the seed data:

`heroku run rake pwb:db:seed`

**Comment by cvillalba** [comment]
Sorry to ask, but does the first command should be run with rake as well ?, and only locally

**Comment by etewiah** [comment]
Ah no, you just need to get to the console first.  So for heroku its: 

`heroku console`

Or locally:

`rails console`

If you wish, you can give me permissions via the heroku dashboard to your app and I'll have a look.

**Comment by cvillalba** [comment]
Thank you very much for the answer.

That fixed everything .

Cheers :smile:

**Comment by etewiah** [comment]
Great to hear.  Looking forward to the pull request with the German translations.
