### ISSUE TITLE
Rails version

### ISSUE THREAD

**Issue by webchi** [etewiah/property_web_builder#25]
Hi. README sad:

> PropertyWebBuilder runs with Rails >= 5.0

But in the bundler:
```
Resolving dependencies...
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.1)

    pwb was resolved to 1.0.0, which depends on
      rails (>= 5.0.0.1, ~> 5.0.0)
```
What version is work?

**Comment by etewiah** [comment]
I use Rails 5.0.3 so I know that works.  I haven't tested with other versions of Rails 5 but I don't know of any particular issues with other versions of Rails 5.
Are you having a problem with the version of rails that you are using?

**Comment by webchi** [comment]
Yes. Bundle could not solve dependencies with rails 5.1.1 It seems pwb frozen to 5.0 version

**Comment by etewiah** [comment]
Hi @webchi , you are right.  I probably shouldn't have that restriction in the gemspec.  I have loosened the restriction on the version of rails and pushed that update to the repository.

Let me know if that fixes it for you.

**Comment by etewiah** [comment]
I believe this issue is resolved so I'll go ahead and close it.
