### ISSUE TITLE
GemRequireError: There was an error while trying to load the gem 'pwb'.

### ISSUE THREAD

**Issue by aelmassry214** [etewiah/property_web_builder#28]
I get this error 

`rails aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'pwb'.
Gem Load Error is: undefined method `before_filter' for ActionController::Base:Class
Did you mean?  before_action
Backtrace for gem load error is:
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paloma-5.0.1/lib/paloma/action_controller_extension.rb:14:in `block in included'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paloma-5.0.1/lib/paloma/action_controller_extension.rb:11:in `module_eval'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paloma-5.0.1/lib/paloma/action_controller_extension.rb:11:in `included'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paloma-5.0.1/lib/paloma/action_controller_extension.rb:171:in `include'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paloma-5.0.1/lib/paloma/action_controller_extension.rb:171:in `<module:Paloma>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paloma-5.0.1/lib/paloma/action_controller_extension.rb:1:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/paloma-5.0.1/lib/paloma.rb:12:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-a520e027a1c0/lib/pwb/engine.rb:9:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-a520e027a1c0/lib/pwb.rb:1:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-a520e027a1c0/lib/pwb.rb:1:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:86:in `block in require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/runtime.rb:75:in `require'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler.rb:106:in `require'
E:/files/ror/projects/realestate1/config/application.rb:7:in `<top (required)>'
E:/files/ror/projects/realestate1/Rakefile:4:in `require_relative'
E:/files/ror/projects/realestate1/Rakefile:4:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Bundler Error Backtrace:
E:/files/ror/projects/realestate1/config/application.rb:7:in `<top (required)>'
E:/files/ror/projects/realestate1/Rakefile:4:in `require_relative'
E:/files/ror/projects/realestate1/Rakefile:4:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
NoMethodError: undefined method `before_filter' for ActionController::Base:Class
Did you mean?  before_action
E:/files/ror/projects/realestate1/config/application.rb:7:in `<top (required)>'
E:/files/ror/projects/realestate1/Rakefile:4:in `require_relative'
E:/files/ror/projects/realestate1/Rakefile:4:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)`

when I run the following command:

`rails pwb:install:migrations`

I am running under windows 10, with postgreSQL installed and the rails application has been created using postgreSQL database.

**Comment by etewiah** [comment]
I think it's to do with this issue

https://github.com/gnclmorais/paloma/pull/1

I'll fix it shortly.

**Comment by etewiah** [comment]
Okay, so there is now a workaround.  I am using a version of the paloma gem which has been fixed.  Because it is not the official version, you will need to add it to your gemfile like so:

```ruby
gem 'pwb', git: 'https://github.com/etewiah/property_web_builder', branch: 'master'
gem 'globalize', git: 'https://github.com/globalize/globalize'
gem 'paloma', github: 'fredngo/paloma'
```
Hope that works.  Please let me know how it goes and what your experience with PropertyWebBuilder is.  Any feedback is always appreciated.

**Comment by aelmassry214** [comment]
Thanks Ed, I will this work around and let you know.

**Comment by aelmassry214** [comment]
okay, that workaround worked well.

However, when executing:

`rails db:migrate`

I get the following error at some point:

`
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateCms < ActiveRecord::Migration[4.2]
E:/files/ror/projects/realestate1/db/migrate/20170725174255_create_cms.pwb.rb:2:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateCms < ActiveRecord::Migration[4.2]
E:/files/ror/projects/realestate1/db/migrate/20170725174255_create_cms.pwb.rb:2:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:migrate`


the error is created while migrating the create cms migration, and I noticed that required version is [4.2],

so I edited this migration to specify the version to be [5.0] as I am using rails 5.1.2,and executed:

`rails db:migrate VERSION:20170725174255`

which is the migration for create cms.

It worked fine, but at some point in the end of the migration I got this error:

`== 20170725174255 CreateCms: migrated (7.9063s) ===============================

rails aborted!
Don't know how to build task 'VERSION:20170725174255' (see --tasks)
bin/rails:4:in `require'
bin/rails:4:in `<main>'`

**Comment by etewiah** [comment]
Mmm, that's strange.  I'll have a look into it now.

**Comment by etewiah** [comment]
Yeah, it looks like from rails 5.1.0 on this has become an issue.  I was using rails 5.0.4.  Can you drop and recreate the db?  That should work.

**Comment by etewiah** [comment]
I'm just going through rails 5.1.0 now and its seems there might be some other issues.  Just looking at that now.

**Comment by aelmassry214** [comment]
ok, and I will try to recreate the db again.

**Comment by aelmassry214** [comment]
well it seems that I had some command with wrong syntax, it should be "=" rather than ":",

it should be:
`rails db:migrate VERSION=20170725174255`

not 

`rails db:migrate VERSION:20170725174255`

no errors occurred when executed the command with '=' and with version [5.0] specified. I will recreate the application again with all the changes and let you know.

**Comment by etewiah** [comment]
Okay, glad to hear.  There was also a minor problem with seeding the database which I have now fixed.  You can update the gem used in your project by running:

```
bundle update pwb
```

**Comment by aelmassry214** [comment]
I updated the gem and when I executed 

`rails pwb:db:seed`

I get this error:

> rails aborted!
ActiveRecord::RecordInvalid: Validation failed: Section must exist
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => pwb:db:seed
(See full trace by running task with --trace)

so, I went ahead and started the server, and went to localhost:3000 the following error occured:

> ActiveRecord::RecordNotFound in Pwb::WelcomeController#index
Couldn't find Pwb::Agency with 'id'=1
Extracted source (around line #189):
        record = statement.execute([id], self, connection).first
        unless record
          raise RecordNotFound.new("Couldn't find #{name} with '#{primary_key}'=#{id}",
                                   name, primary_key, id)
        end
        record

**Comment by etewiah** [comment]
Okay, it looks like there are a few more issues with rails 5.1.0.  I'll create a branch to fix those but as I'm busy with some other projects it will not be ready this week.
Please try with rails 5.0.4 as I know that works.  ( I will update the readme too ).

**Comment by aelmassry214** [comment]
Thanks Ed, I will await the new branch

**Comment by etewiah** [comment]
I think its better you go ahead with rails 5.0.4.  It is a supported current release ( released about the same time as 5.1.2:  https://rubygems.org/gems/rails/versions ) and everything works okay. 
Right now its hard to say when I can finish work on the other branch.

**Comment by etewiah** [comment]
The master branch should support Rails 5.1.0 now.

**Comment by aelmassry214** [comment]
Thanks Ed,
I tried the application with older version and now I tried with the new branch.

everything, worked great without errors now on Rails 5.1.0.

However, when I started the server and went to localhost:3000 the following error appeared:

> ComfortableMexicanSofa::MissingSite in Pwb::WelcomeController#index
    Cannot find CMS Site with identifier: localhost//
    Extracted source (around line #49):
    if (page_path = options.delete(:cms_page)) || (layout_identifier = options.delete(:cms_layout))
        unless @cms_site ||= Comfy::Cms::Site.find_site(request.host.downcase, request.fullpath)
          raise ComfortableMexicanSofa::MissingSite.new("#{request.host.downcase}/#{request.fullpath}")
        end
      end

**Comment by etewiah** [comment]
Hi @aelmassry214 , I suspect you are on the cms-pages branch.  Please switch to the master branch and try again.

**Comment by etewiah** [comment]
Hi @aelmassry214 , can you please confirm that everything is working okay now.

**Comment by etewiah** [comment]
@aelmassry214, as I have not heard back from you I will close the issue.
