### ISSUE TITLE
Routing Error - Bad Gateway

### ISSUE THREAD

**Issue by messyjessy** [etewiah/property_web_builder#37]
I need help with this, please. 

Every time I set routes to:
mount Pwb::Engine => '/' 
root to: 'welcome#index'

My app times out and I get a bad gateway error.

**Comment by etewiah** [comment]
A bad gateway error suggests to me that you are not even getting to the PropertyWebBuilder engine.  You will have to give me more details if you want me to help.
How are you running your server?  What happens when you browse a normal route on your server? What is the full message you receive?  etc.

**Comment by messyjessy** [comment]
I'm running the app on Cloud9. All other routes seem to be working
properly. I'm not sure if I missed something during installation or what
happened. When I place "mount Pwb::Engine => '/' " at the top of my
route.rb file, I get this error message:

<html>

  <head>
    <meta charset='utf-8'>
    <title>Error 502 - Bad Gateway</title>
    <link rel="stylesheet" type="text/css"
href="https://cdn.c9.io/errors/style.css" />
    <style type="text/css">
    .error_content {
        background: rgba(255, 255, 255, 0.23);
        padding: 10px;
        width: 641px;
        margin: 25px 0;
        display: none;
    }

    #error-msg {
        display: block;
    }
    </style>
  </head>
  <body class="errorUnknown light">
    <div id="wrapper">
      <h1>Error 502 - Bad Gateway</h1>
      <div class="error_content" id="error-msg">
          <p>Please click <a
href="javascript:location.reload(true)">here</a> to try again, if the
issue persists please contact <a
href="https://c9.io/support">support</a></p>
      </div>

      <a href="http://status.c9.io">Status Page</a> |
      <a href="https://c9.io/support">Support</a> |
      <a href="https://c9.io/dashboard.html">Dashboard</a> |
      <a href="https://c9.io">Home</a>
    </div>
  </body>
</html>

**Comment by etewiah** [comment]
I don't know how cloud9 works but a 502 error is usually an issue with the server setup rather than the application.  If you look at the cloud 9 forums you will see a lot of issues about bad gateway errors:

https://community.c9.io/t/502-bad-gateway/17968

I suggest you ask for help there directly.  This does not seem to be an issue with PropertyWebBuilder.

**Comment by etewiah** [comment]
Hello @messyjessy - were you able to resolve this issue with cloud 9?

**Comment by etewiah** [comment]
Hi @messyjessy, as you are not replying to me I will go ahead and close this issue.  Let me know if I can help with anything else.
