### ISSUE TITLE
Is it possible to use my own domain with PropertyWebBuilder on heroku?

### ISSUE THREAD

**Issue by etewiah** [etewiah/property_web_builder#39]
Asking this on behalf of @acsmartinho.

**Comment by etewiah** [comment]
@acsmartinho, it is possible to use your own domain with heroku.  You can find the instructions here:

https://devcenter.heroku.com/articles/custom-domains

**Comment by anoopkanyan** [comment]
It is possible to use your custom domain to point to the application on Heroku. I did it today itself. [homeclickaway](http://www.homeclickaway.com/l)

**Comment by etewiah** [comment]
Nice @anoopkanyan - keep me updated on how it goes (ed at propertywebbuilder.com).  Right now I am not keeping track of who is using PWB but I would like to do so in future.
