### ISSUE TITLE
Currencies

### ISSUE THREAD

**Issue by Zaldor** [etewiah/property_web_builder#42]
Could it be possible to convert automatically currency based on user language choice?

**Comment by etewiah** [comment]
Funny you should ask.  Someone is working with me to learn more about Rails through this project.  Right now she is looking at an instant currency converter.  It won't be based on language choice.  Rather there will be a dropdown allowing users to select a currency.

**Comment by etewiah** [comment]
This is no longer a priority for the project.  Closing this issue to focus on more important requirements.
