### ISSUE TITLE
Can't Add Description 

### ISSUE THREAD

**Issue by Zaldor** [etewiah/property_web_builder#44]
Site installed and updated, configured to use italian languange, but when trying to add a property adding TITLE and Description to it doesn't seam to work (it does for english)
https://carusoimmobiliare.herokuapp.com/it/properties/for-sale/51/show
Default admin USR:PWD

**Comment by etewiah** [comment]
Looks like it is a bug specific to Italian - let me just have a look now.

**Comment by etewiah** [comment]
Okay, I see what the problem is.  I will push out a fix as soon as I can.

**Comment by Zaldor** [comment]
Thanks!

Il dom 3 dic 2017, 19:59 Ed Tewiah <notifications@github.com> ha scritto:

**Comment by etewiah** [comment]
Hi @Zaldor - I've pushed out a fix.  Please update to the latest build and let me know if it works.

**Comment by Zaldor** [comment]
Seams to works. great!

**Comment by etewiah** [comment]
Cool, I'll go ahead and close this issue then.
