### ISSUE TITLE
Cannot login to my propertyweb builder app on heroku. I don't have admin credentials help me out on this.  

### ISSUE THREAD

**Issue by sairaman** [etewiah/property_web_builder#45]
cannot login with default heroku login credentials and i didn't receive any email from property web builder when i deployed the app. Please help me find the user name and password to login to  admin panel on real99.herokuapp.com

**Comment by etewiah** [comment]
Hello @sairaman , the default credentials documented in the readme work.  

User admin@example.com with a password of "pwb123456"

**Comment by etewiah** [comment]
Hi @sairaman, can you please confirm that you have been able to access your site?

**Comment by sairaman** [comment]
Hello Ed Tewaiah!! thanks for your valuable support, i am sorry that i was
lazy to try the user name as mentioned in Readme file. This was a wonderful
cms, and i love using it. Thanks again for giving us this great
application.

**Comment by etewiah** [comment]
Glad you like it ;)  Any questions / feedback just let me know.

**Comment by sairaman** [comment]
Sure Tewaiah, we will let you know :)
