### ISSUE TITLE
views render error

### ISSUE THREAD

**Issue by itgroupservices111** [etewiah/property_web_builder#47]
Missing template C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-8904e7bd8ce3/app/themes/default/views/layouts/pwb/application with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in: * "C:/Users/zafar/Documents/GitHub/pwb-for-heroku/app/themes/default/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-8904e7bd8ce3/app/themes/default/views" * "C:/Users/zafar/Documents/GitHub/pwb-for-heroku/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/property_web_scraper-6f6d25ef2014/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-8904e7bd8ce3/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/devise-4.3.0/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/paloma-40a84f5dfa5d/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/paloma-40a84f5dfa5d/app/views"
Extracted source (around line #46):

**Comment by etewiah** [comment]
Please provide some details of what you did and at what point you got this error.

**Comment by itgroupservices111** [comment]
git clone https://github.com/etewiah/pwb-for-heroku.git
cd pwb-for-heroku
rails db:create
rails db:migrate
rails pwb:db:seed
rails pwb:db:seed_pages
rail server

**Comment by etewiah** [comment]
I suspect you might not have cloned and installed the project successfully.   Try running:

`bundle install`

If that does not fix it then delete the directory and start again.  I have tested myself today and I know it works.

**Comment by BritAlbritton** [comment]
I'm afraid I have the same error on Windows 7, running Ruby 2.4.3-1-x64, Rails 5.1.4, gem v. 2.75,  and PostgreSQL10. 

I deleted and tried again, ran bundle install, etc. No dice. 

Here's what shows up at http://localhost:3000/ :

Missing template D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views/layouts/pwb/application with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in: * "D:/Ruby/pwb-for-heroku/app/themes/default/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views" * "D:/Ruby/pwb-for-heroku/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_scraper-6f6d25ef2014/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/devise-4.4.1/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/views" 

Extracted source (around line #46): 
    def find(*args)
      find_all(*args).first || raise(MissingTemplate.new(self, *args))
    end

    def find_file(path, prefixes = [], *args)

**Comment by etewiah** [comment]
Hi @BritAlbritton , I will follow up on this in the issue you opened here:

https://github.com/etewiah/property_web_builder/issues/61
