### ISSUE TITLE
Throws error when going to send contact email

### ISSUE THREAD

**Issue by marquicus** [etewiah/property_web_builder#48]
Thrown error:

Lo sentimos, ha ocurrido un error.
×
undefined method `client=' for #<Pwb::Message:0x00007fdf00211128> Did you mean? client_id=

Environments: development, production

**Comment by marquicus** [comment]
The fix I found in file ./app/mailers/pwb/enquiry_mailer.rb

-      @enquiry.client = @client
+      @enquiry.client_id = @client
       @enquiry.save

Have you considered to use reCAPTCHA?

**Comment by etewiah** [comment]
Hi @marquicus, good catch - thanks for pointing that out.  I will fix it as soon as I get the chance (and expand my tests so it doesn't happen again ;)
Regarding reCAPTCHA, it is on my todo list but I haven't got round to doing it yet.  If it is important for you, just let me know and I will prioritise it.
Also, many thanks for supporting me on opencollective.  As the first person to do so I really appreciate it - if there is anything I can do to help feel free to contact me directly ( ed at propertywebbuilder.com )

**Comment by marquicus** [comment]
Hi Ed, thank you so much for feedback.
I'm very interested in this project and I would like to do a better contribution to the project with workforce for testging or develpment or other ideas, I'll send you my suggestions to your contact email.

Regards 
Marco

**Comment by etewiah** [comment]
This issue has now been fixed and tests added to catch any future errors.

(Marco, I received your email and have replied.)

**Comment by marquicus** [comment]
Hi @etewiah , thank you
I found same issue for props_controller.rb, but this is the fix, do you want me to reopen the issue or this notification is sufficient

--- a/app/controllers/pwb/props_controller.rb
+++ b/app/controllers/pwb/props_controller.rb
@@ -91,7 +91,7 @@ module Pwb
 
-      @enquiry.client = @client
+      @enquiry.client_id = @client
       @enquiry.save

I'm working in the environment

**Comment by etewiah** [comment]
Hi @marquicus , it is fixed there too.  The problem was that the client model has now been replaced by the contact model.  This is in preparation for adding contact management functionality (https://github.com/etewiah/property_web_builder/issues/36)

If you look at line 94 here you will see that I now assign a contact instead of a client:
https://github.com/etewiah/property_web_builder/blob/master/app/controllers/pwb/props_controller.rb
