### ISSUE TITLE
Template is missing

### ISSUE THREAD

**Issue by itgroupservices111** [etewiah/property_web_builder#57]
error Template is missing ????

Missing template C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-e16817d6f369/app/themes/default/views/layouts/pwb/application with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in: * "C:/Users/zafar/pwb-for-heroku/app/themes/default/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-e16817d6f369/app/themes/default/views" * "C:/Users/zafar/pwb-for-heroku/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/property_web_scraper-6f6d25ef2014/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/property_web_builder-e16817d6f369/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/devise-4.4.0/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/paloma-40a84f5dfa5d/app/views" * "C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/bundler/gems/paloma-40a84f5dfa5d/app/views"

**Comment by etewiah** [comment]
Congratulations - you have opened the most pointless and unhelpful issue I have come across.  If you cannot take 5 minutes to explain a bit about what you were doing when the error occured do not expect me to spend any time helping you.

**Comment by BritAlbritton** [comment]
Hi, Etewiah,

Your gem is beautiful, and I'd very much like to deploy it locally. As I wrote in another thread where a similar error was reported, this is happening to me as well on Windows 7 professional running Ruby24-x64 with Rails 5.1.4, gem 2.7.5, and PostgreSQL 10.2.

After following your steps:
git clone https://github.com/etewiah/pwb-for-heroku.git
cd pwb-for-heroku
rails db:create
rails db:migrate
rails pwb:db:seed
rails pwb:db:seed_pages

Even after deleting and reinstalling from git, I get:
Action Controller: Exception caught

Missing template D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views/layouts/pwb/application with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in: * "D:/Ruby/pwb-for-heroku/app/themes/default/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views" * "D:/Ruby/pwb-for-heroku/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_scraper-6f6d25ef2014/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/devise-4.4.1/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/views" 

Extracted source (around line #46): 

    def find(*args)
      find_all(*args).first || raise(MissingTemplate.new(self, *args))
    end

    def find_file(path, prefixes = [], *args)

Any suggestions?

**Comment by etewiah** [comment]
Hi @BritAlbritton , thanks for providing the extra information - with that I can now investigate better.  As you have opened another ticket for this issue I will post my updated there:

https://github.com/etewiah/property_web_builder/issues/61
