### ISSUE TITLE
Broken links in admin

### ISSUE THREAD

**Issue by SteveRedka** [etewiah/property_web_builder#60]
There are three broken links in [admin dashboard](https://propertywebbuilder.herokuapp.com/en/admin/dashboard)

* `Edit landing page`
* `Change 'About Us' text`
* `Change 'Legal' texts`

**Comment by etewiah** [comment]
Well spotted @SteveRedka - I changed the way those items are handled and forgot to update the links.  Will update it as soon as I get the chance (as it isn't a high priority issue I probably won't get to it for a few days though)
Thanks for pointing it out.  Hope you find PWB useful

**Comment by etewiah** [comment]
Admin dashboard links fixed
