### ISSUE TITLE
Missing template

### ISSUE THREAD

**Issue by BritAlbritton** [etewiah/property_web_builder#61]
Hi, Etewiah,

Your gem is beautiful, and I'd very much like to deploy it locally to test it. 

As I wrote in two closed threads where a similar error was reported, like others I'm getting an "Action Controller: Exception caught" error. My installation is on Windows 7 Professional, and I'm running Ruby24-x64 with Rails 5.1.4, gem 2.7.5, and PostgreSQL 10.2.

After following your steps:
git clone https://github.com/etewiah/pwb-for-heroku.git
cd pwb-for-heroku
rails db:create
rails db:migrate
rails pwb:db:seed
rails pwb:db:seed_pages
rails server

Even after deleting and reinstalling from git, at http://localhost:3000/ I get:
Action Controller: Exception caught

Missing template D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views/layouts/pwb/application with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in: * "D:/Ruby/pwb-for-heroku/app/themes/default/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views" * "D:/Ruby/pwb-for-heroku/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_scraper-6f6d25ef2014/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/devise-4.4.1/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/views" 

Extracted source (around line #46): 

    def find(*args)
      find_all(*args).first || raise(MissingTemplate.new(self, *args))
    end

    def find_file(path, prefixes = [], *args)

I don't see a themes/ directory, even after I ran a build. I ran the Ruby command prompt as an administrator just in case there was a permissions error. 

I've also tried:
bundle install
bundle update pwb

I even tried copying the themes directory from the property_web_builder git, which was probably a sign of my own unfamiliarity with Ruby, but also didn't work.  

Any suggestions?

**Comment by BritAlbritton** [comment]
I've also run bundle config git.allow_insecure true to get rid of a notice. No luck.

**Comment by etewiah** [comment]
Hi @BritAlbritton, thanks for trying out PWB.  Can you let me know what files you have in this directory on your local machine?

D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views/layouts/pwb/

I suspect it is something to do with how the files are handled by Windows.  I use Osx and I don't have access to a Windows machine to try it out.  If there is indeed an application.html.erb file in the directory above then the issue is probably to do with permissions.  Perhaps we can set up a skype call so I can help you troubleshoot it.

**Comment by BritAlbritton** [comment]
Thanks for getting back to me so quickly. Yes, I do have the file application.html.erb in that folder.

If it is a problem with with Ruby on Windows, this sort of thing must have happened before. Let me poke around StackExchange, etc.

**Comment by BritAlbritton** [comment]
OK. Here are the notices I get when I run rails server:
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
  Please add the following to your Gemfile to avoid polling for changes:
    gem 'wdm', '>= 0.1.0' if Gem.win_platform?
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.3-p205), codename: Russell's Teapot
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://0.0.0.0:3000
Use Ctrl-C to stop

**Comment by BritAlbritton** [comment]
I tried gem install wdm, but I still get the first warning:
Please add the following to your Gemfile to avoid polling for changes:
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

(It had no effect on what I see at localhost:3000)

**Comment by BritAlbritton** [comment]
Here's what I get in the Ruby command prompt when I visit localhost:3000:

Started GET "/" for 127.0.0.1 at 2018-02-09 12:32:45 -0500
   (69.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER
 BY "schema_migrations"."version" ASC
Processing by Pwb::WelcomeController#index as HTML
  Pwb::Agency Load (80.8ms)  SELECT  "pwb_agencies".* FROM "pwb_agencies" WHERE
"pwb_agencies"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Pwb::Website Load (36.6ms)  SELECT  "pwb_websites".* FROM "pwb_websites" WHERE
 "pwb_websites"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Pwb::Link Load (101.2ms)  SELECT  "pwb_links".* FROM "pwb_links" WHERE "pwb_li
nks"."slug" = $1 LIMIT $2  [["slug", "top_nav_admin"], ["LIMIT", 1]]
  CACHE Pwb::Website Load (0.0ms)  SELECT  "pwb_websites".* FROM "pwb_websites"
WHERE "pwb_websites"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  CACHE Pwb::Website Load (0.0ms)  SELECT  "pwb_websites".* FROM "pwb_websites"
WHERE "pwb_websites"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  CACHE Pwb::Website Load (0.0ms)  SELECT  "pwb_websites".* FROM "pwb_websites"
WHERE "pwb_websites"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Pwb::PageContent Load (69.6ms)  SELECT  "pwb_page_contents".* FROM "pwb_page_c
ontents" WHERE "pwb_page_contents"."website_id" = $1 AND "pwb_page_contents"."vi
sible_on_page" = $2 AND "pwb_page_contents"."page_part_key" = $3 ORDER BY sort_o
rder asc LIMIT $4  [["website_id", 1], ["visible_on_page", "t"], ["page_part_key
", "footer_content_html"], ["LIMIT", 1]]
  Pwb::Content Load (56.6ms)  SELECT  "pwb_contents".* FROM "pwb_contents" WHERE
 "pwb_contents"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Pwb::ContentPhoto Load (42.2ms)  SELECT  "pwb_content_photos".* FROM "pwb_cont
ent_photos" WHERE "pwb_content_photos"."block_key" = $1 LIMIT $2  [["block_key",
 "landing_img"], ["LIMIT", 1]]
  Pwb::Page Load (42.2ms)  SELECT  "pwb_pages".* FROM "pwb_pages" WHERE "pwb_pag
es"."slug" = $1 LIMIT $2  [["slug", "home"], ["LIMIT", 1]]
  Pwb::Page::Translation Load (0.0ms)  SELECT "pwb_page_translations".* FROM "pw
b_page_translations" WHERE "pwb_page_translations"."pwb_page_id" = $1  [["pwb_pa
ge_id", 5]]
Completed 401 Unauthorized in 1793ms (ActiveRecord: 653.8ms)



ActionView::MissingTemplate (Missing template D:/Ruby24-x64/lib/ruby/gems/2.4.0/
bundler/gems/property_web_builder-468812b040a0/app/themes/default/views/layouts/
pwb/application with {:locale=>[:en], :formats=>[:html], :variants=>[], :handler
s=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:
  * "D:/Ruby/pwb-for-heroku/app/themes/default/views"
  * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b
040a0/app/themes/default/views"
  * "D:/Ruby/pwb-for-heroku/app/views"
  * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_scraper-6f6d25e
f2014/app/views"
  * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b
040a0/app/views"
  * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/devise-4.4.1/app/views"
  * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/view
s"
  * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/view
s"
):

actionview (5.1.4) lib/action_view/path_set.rb:46:in `find'
actionview (5.1.4) lib/action_view/lookup_context.rb:116:in `find'
actionview (5.1.4) lib/action_view/renderer/abstract_renderer.rb:18:in `find_tem
plate'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:87:in `resolve_
layout'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:94:in `resolve_
layout'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:74:in `find_lay
out'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:58:in `render_w
ith_layout'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:50:in `render_t
emplate'
actionview (5.1.4) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (5.1.4) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (5.1.4) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (5.1.4) lib/action_view/rendering.rb:103:in `_render_template'
actionpack (5.1.4) lib/action_controller/metal/streaming.rb:217:in `_render_temp
late'
actionview (5.1.4) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (5.1.4) lib/action_controller/metal/rendering.rb:52:in `render_to_bod
y'
actionpack (5.1.4) lib/action_controller/metal/renderers.rb:141:in `render_to_bo
dy'
actionpack (5.1.4) lib/abstract_controller/rendering.rb:24:in `render'
actionpack (5.1.4) lib/action_controller/metal/rendering.rb:36:in `render'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:44:in `block (
2 levels) in render'
activesupport (5.1.4) lib/active_support/core_ext/benchmark.rb:12:in `block in m
s'
D:/Ruby24-x64/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
activesupport (5.1.4) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:44:in `block i
n render'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:87:in `cleanup
_view_runtime'
activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:29:in `cle
anup_view_runtime'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:43:in `render'

D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0
/app/controllers/pwb/welcome_controller.rb:22:in `index'
actionpack (5.1.4) lib/action_controller/metal/basic_implicit_render.rb:4:in `se
nd_action'
actionpack (5.1.4) lib/abstract_controller/base.rb:186:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/rendering.rb:30:in `process_actio
n'
actionpack (5.1.4) lib/abstract_controller/callbacks.rb:20:in `block in process_
action'
activesupport (5.1.4) lib/active_support/callbacks.rb:131:in `run_callbacks'
actionpack (5.1.4) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:32:in `block i
n process_action'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `block in instr
ument'
activesupport (5.1.4) lib/active_support/notifications/instrumenter.rb:21:in `in
strument'
activesupport (5.1.4) lib/active_support/notifications.rb:166:in `instrument'
actionpack (5.1.4) lib/action_controller/metal/instrumentation.rb:30:in `process
_action'
actionpack (5.1.4) lib/action_controller/metal/params_wrapper.rb:252:in `process
_action'
activerecord (5.1.4) lib/active_record/railties/controller_runtime.rb:22:in `pro
cess_action'
actionpack (5.1.4) lib/abstract_controller/base.rb:124:in `process'
actionview (5.1.4) lib/action_view/rendering.rb:30:in `process'
actionpack (5.1.4) lib/action_controller/metal.rb:189:in `dispatch'
actionpack (5.1.4) lib/action_controller/metal.rb:253:in `dispatch'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:31:in `serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
railties (5.1.4) lib/rails/railtie.rb:185:in `public_send'
railties (5.1.4) lib/rails/railtie.rb:185:in `method_missing'
actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:
Constraints>'
actionpack (5.1.4) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `each'
actionpack (5.1.4) lib/action_dispatch/journey/router.rb:33:in `serve'
actionpack (5.1.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.4) lib/rack/etag.rb:25:in `call'
rack (2.0.4) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.4) lib/rack/head.rb:12:in `call'
rack (2.0.4) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in c
all'
activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `cal
l'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call
'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagge
d'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
request_store (1.4.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.4) lib/rack/method_override.rb:22:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.r
b:27:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.10.0) lib/puma/configuration.rb:225:in `call'
puma (3.10.0) lib/puma/server.rb:605:in `handle_request'
puma (3.10.0) lib/puma/server.rb:437:in `process_client'
puma (3.10.0) lib/puma/server.rb:301:in `block in run'
puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by BritAlbritton** [comment]
Note that to get the rails db:create and rails db:migrate to work, I added a superuser username and password to the default: &default section of pwb-for-heroku/config/database.yml

**Comment by etewiah** [comment]
Very strange.  I can do a very quick skype now if you want (but will have to be in the next 5 minutes or so)

**Comment by BritAlbritton** [comment]
Thanks for offering, but now's not a good time. But if you have suggestions for where I might start, I'm happy to do some legwork.

**Comment by etewiah** [comment]
If you want to troubleshoot by yourself I would suggest editing this file
D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0
/app/controllers/pwb/welcome_controller.rb

For example you could add " , render layout: false " to the end of line 22 there to see what happens. 

You can also try setting a breakpoint in the set_theme_path function of the application_controller in the same directory and poking about to see if there is an issue with the layout that gets set there.

For the breakpoint, put "byebug" on a single line.  When you refresh the webpage, your console should stop at that line and allow you to examine it.

**Comment by etewiah** [comment]
I have to go shortly but I will check here again in a few hours to see if you have any further questions.

**Comment by BritAlbritton** [comment]
Thanks. Is there a similar but simpler project to yours I might try installing as another way to narrow things down? Something with the same dependencies but much less going on?

**Comment by etewiah** [comment]
Can't think of something off the top of my head.  The issue is almost certainly related to the set_theme_path function in the application controller so if you poke about there a bit I'm pretty sure you'll figure it out.

**Comment by etewiah** [comment]
BTW, when you browse to "/admin" that works right?

**Comment by BritAlbritton** [comment]
I'm afraid not
http://localhost:3000/admin
takes me to
http://localhost:3000/en/users/sign_in

which shows the same:
Missing template D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views/layouts/pwb/application with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in: * "D:/Ruby/pwb-for-heroku/app/themes/default/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/themes/default/views" * "D:/Ruby/pwb-for-heroku/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_scraper-6f6d25ef2014/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/property_web_builder-468812b040a0/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/devise-4.4.1/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/views" * "D:/Ruby24-x64/lib/ruby/gems/2.4.0/bundler/gems/paloma-40a84f5dfa5d/app/views"
