### ISSUE TITLE
Changing logo through admin works only once

### ISSUE THREAD

**Issue by SteveRedka** [etewiah/property_web_builder#64]
If you use interface to change logo, it uploads an image - but keeps using the first uploaded logo.

[![2018-02-20-170228_1366x768_scrot.png](https://s14.postimg.org/eik0v8q7l/2018-02-20-170228_1366x768_scrot.png)](https://postimg.org/image/vvuba3lil/)

**Comment by etewiah** [comment]
Hi @SteveRedka, you are right.  I came across this issue a few days ago and I implemented the following workaround:

https://github.com/etewiah/property_web_builder/commit/725b307f4056c21210bee49b77e61d0e9758bb63

Update to the latest version and it should work.
I will review the way I've implemented photo updates when I get the chance.

**Comment by etewiah** [comment]
Hi @SteveRedka, can you confirm that I can close this issue?
