### ISSUE TITLE
cannot use geokit or Geocoder inside property_web_builder engine

### ISSUE THREAD

**Issue by prateekdarmwal1** [etewiah/property_web_builder#71]
I was customizing the property_web_builder engine for getting nearby results using Geokit or Geocoder gem, but can't use any of it.
getting undefined method 'gecoded_by' using 'Geocoder' gem and undefined method 'acts_as_mappable' for 'geokit-rails' gem.

Here is what I was doing -
For **geokit-rails**

> module Pwb
  class Prop < ApplicationRecord
    translates :title, :description
    globalize_accessors locales: I18n.available_locales
    attribute :title
    attribute :description
    acts_as_mappable :default_units => :miles,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

For **Geocoder**

> module Pwb
  class Prop < ApplicationRecord
    translates :title, :description
    globalize_accessors locales: I18n.available_locales
    attribute :title
    attribute :description
    geocoded_by :complete_address
    after_validation :geocode

When I try finding the results in rails console after adding the engine on project as described in readme. I get these results.

> p = Pwb::Prop.first
NoMethodError: undefined method `acts_as_mappable' for #<Class:0x007f04ecda5118>
	from (irb):1

**Comment by prateekdarmwal1** [comment]
Added gem to application instead of pwb engine and it worked. Closing issue now.

**Comment by etewiah** [comment]
Hi @prateekdarmwal1 , the Geocoder gem works fine with the PWB gem.  You can see here that I'm using it at line 9:

https://github.com/etewiah/property_web_builder/blob/master/app/models/pwb/prop.rb

Perhaps you were using an older version of the gem.....   Anyway, I'm glad you found a workaround.

**Comment by prateekdarmwal** [comment]
Hi @etewiah, Yes I might be using an older version but my issue was resolved. By the way thanks for your reply its good to see that you guys are continuously watching all issues. Great Job!

**Comment by etewiah** [comment]
Cool.  We're working on a new approach to the front end using vue js.  Its early days still but it will make it much easier to modify the look and feel:

https://github.com/etewiah/pwb-themes-base
