### ISSUE TITLE
Validation failed: Page must exist

### ISSUE THREAD

**Issue by fercreek** [etewiah/property_web_builder#72]
Hi!

I'm installing an existing app, well my issue is when I'm running
`rails pwb:db:seed` I have an error similar to #38 

My environment
```
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
Rails 5.1.5
```

![image](https://user-images.githubusercontent.com/6548504/37698192-06315fce-2ca7-11e8-91ed-07043155cdf8.png)

**Comment by etewiah** [comment]
Hi @fercreek , are you following the instructions in the readme for "Install as a standalone site" or the instructions for "Installation within an existing Rails app"?

**Comment by fercreek** [comment]
@etewiah Installation within an existing Rails app

**Comment by etewiah** [comment]
Please follow the instructions in the readme for "Install as a standalone site" to confirm that works.  Installing within an existing rails app is more tricky as you may have something in there that causes issues and I won't be able to identify what it is without knowing a lot more about the rails app you created.

**Comment by fercreek** [comment]
I created a new app. It's okay for you if I show you the Gemfile?  Anyways, let me try with Standalone Site

**Comment by fercreek** [comment]
Using `Install as a standalone site` works.
