### ISSUE TITLE
pwb:db:seed error

### ISSUE THREAD

**Issue by nuno84** [etewiah/property_web_builder#76]
Hi,
I am trying to install the demo using the seeds but it fails:

rails pwb:db:seed

Contents seed for ar not found
Contents seed for ca not found
Contents seed for de not found
rails aborted!
ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved

What can I do?
Thank you

**Comment by etewiah** [comment]
Hello @nuno84 , can you please run the command with the "--trace" option and paste the full output in a gist so I can understand better what has happened.

**Comment by nuno84** [comment]
Hi etewiah,
Sure, the output is pasted below.
But this is the same issue that happens when I try to change some HTML code in any section, lets say for instance in the footer...
Please see the console output for both situations below.
Thank you

 **console output for the  page fragmento edition**

Started PUT "/api/v1/pages/page_fragment" for 192.168.1.66 at 2018-06-19 09:10:45 +0100
Cannot render console from 192.168.1.66! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
  Pwb::User Load (0.5ms)  SELECT  "pwb_users".* FROM "pwb_users" WHERE "pwb_users"."id" = $1 ORDER BY "pwb_users"."id" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ /home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
Processing by Pwb::Api::V1::PageController#save_page_fragment as JSON
  Parameters: {"page_slug"=>"contact-us", "fragment_details"=>{"blocks"=>{"main_content"=>{"content"=>"<p>Contact-us demo text</p>"}}, "locale"=>"en", "page_part_key"=>"content_html"}}


ActiveRecord::RecordNotSaved (You cannot call create unless the parent is saved):
  
activerecord (5.2.0) lib/active_record/associations/singular_association.rb:67:in `_create_record'
activerecord (5.2.0) lib/active_record/associations/association.rb:182:in `create'
activerecord (5.2.0) lib/active_record/associations/builder/singular_association.rb:33:in `create_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/app/services/pwb/page_part_manager.rb:20:in `find_or_create_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/app/services/pwb/page_part_manager.rb:165:in `rebuild_page_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/app/services/pwb/page_part_manager.rb:104:in `update_page_part_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/app/controllers/pwb/api/v1/page_controller.rb:80:in `save_page_fragment'
actionpack (5.2.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.0) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.0) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.0) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.0) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.0) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.0) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.0) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.0) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.0) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.0) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.0) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.0) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.0) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.0) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (5.2.0) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
railties (5.2.0) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.0) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.0) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.0) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.0) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.0) lib/action_dispatch/routing/route_set.rb:840:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.5) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.0) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.6.2) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.6.2) lib/web_console/middleware.rb:22:in `block in call'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `catch'
web-console (3.6.2) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'


**--------------------- pwb:db:seed output**
rails aborted!
ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activerecord-5.2.0/lib/active_record/associations/singular_association.rb:67:in `_create_record'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activerecord-5.2.0/lib/active_record/associations/association.rb:182:in `create'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activerecord-5.2.0/lib/active_record/associations/builder/singular_association.rb:33:in `create_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/app/services/pwb/page_part_manager.rb:20:in `find_or_create_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/app/services/pwb/page_part_manager.rb:165:in `rebuild_page_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/app/services/pwb/page_part_manager.rb:104:in `update_page_part_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/app/services/pwb/page_part_manager.rb:94:in `seed_container_block_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/lib/pwb/contents_seeder.rb:67:in `set_page_part_content'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/lib/pwb/contents_seeder.rb:40:in `block in seed_content_for_locale'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:41:in `each'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activerecord-5.2.0/lib/active_record/relation/delegation.rb:41:in `each'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/lib/pwb/contents_seeder.rb:36:in `seed_content_for_locale'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/lib/pwb/contents_seeder.rb:19:in `block in seed_page_content_translations!'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/lib/pwb/contents_seeder.rb:13:in `each'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/lib/pwb/contents_seeder.rb:13:in `seed_page_content_translations!'
/home/nuno/Documents/RubymineWorkspace/property_web_builder/lib/tasks/pwb_tasks.rake:24:in `block (3 levels) in <main>'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/home/nuno/Documents/RubymineWorkspace/Proj/Proj/bin/rails:9:in `<top (required)>'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/spring-2.0.2/lib/spring/binstub.rb:25:in `load'
/home/nuno/.rvm/gems/ruby-2.3.4@Proj/gems/spring-2.0.2/lib/spring/binstub.rb:25:in `<top (required)>'
/home/nuno/Documents/RubymineWorkspace/Proj/Proj/bin/spring:15:in `<top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => pwb:db:seed
(See full trace by running task with --trace)

**Comment by etewiah** [comment]
I really can't figure out what is happening.  Does this happen with a completely clean database?  I'm thinking that you might have mounted the PWB engine onto an app that already has data that might somehow be causing an issue.

You can find out what is going on by adding a breakpoint at line 36 in this file:
/home/nuno/Documents/RubymineWorkspace/property_web_builder/lib/pwb/contents_seeder.rb

Just type the word "byebug" on a line by itself and rerun the command.  The code will pause execution at that point and return the console so you can examine what exactly is going on.

**Comment by nuno84** [comment]
Hi etewiah,
The database is clean but that is not necessary per se.
The problem is both with seeding as well as when we want to edit some html through the backoffice.
I used debug to see where it fails and the problem is essentially this: "You cannot call create unless the parent is saved".
You have a function to create a join model in app/services/pwb/find_or_create_join_model.rb 
The problem is that the code is trying to save a property when it's parent is not saved yet.
I guess you can you figure it out faster than me and doing less mess than me...
Thank you

**Comment by etewiah** [comment]
I suspect this has something to do with changes in Rails 5.2.   I have been working with Rails 5.1.   When I get the chance I will upgrade to 5.2 and do some tests with that.

**Comment by nuno84** [comment]
Hi again,
I tried to create a new project using rails 5.1.6 and the error is the same.
It is easy to recreate...
Just create a blank database, migrate and seed and it will fail.
Thank you for your attention.

**Comment by etewiah** [comment]
Hi there, sorry about the delay - I've been super busy.  I did upgrade Rails and did not encounter any issues so I really don't know what is happening.

We can setup a skype call to have a closer look if you wish.
