### ISSUE TITLE
JS bug?

### ISSUE THREAD

**Issue by nuno84** [etewiah/property_web_builder#78]
Hi etewiah,
I've been working and evaluating your project.
I found some minor bugs and tried to understand and contribute, but as I can see, the JS section has been minified and thus, impossible to edit.
For instance, I was trying to understand why the item in the image below has the buttons active (it is the only one), but it is processed in the JS and thus, I cannot get it.
Thank you

![image](https://user-images.githubusercontent.com/5565536/41542121-1e122082-730c-11e8-8d4d-33205715eb0d.png)

**Comment by etewiah** [comment]
Hi @nuno84 , thanks for your interest in the project.  

The code for the javascript used by the admin panel is here:

https://github.com/etewiah/property_web_builder_admin

It is built with ember.js but I am working on migrating it to vue.js:

https://github.com/etewiah/property_web_builder/issues/49

What you have noticed is not a bug.  When you change the text, those buttons appear so you can either save or cancel your change.

**Comment by nuno84** [comment]
Hi etewiah,
The interesting is that I didn't change the text at all but those buttons appeared by default on that item.
I was going to chase the issue but then I couldn't read the JS.
Also, note that the tooltips say that it couldn't find the translation and I am not sure where (the language is in English, but it also fails in other languages)
Thank you

![image](https://user-images.githubusercontent.com/5565536/41584773-0aecc3c4-73a0-11e8-89aa-234aa84582f2.png)
