### ISSUE TITLE
Dependencies problem when deploy (not in heroku)

### ISSUE THREAD

**Issue by cvillalba** [etewiah/property_web_builder#8]
Hi, first of all great project, thanks for open-sourced it.

I've been trying to deploy the project un my server and locally, and I'm getting a dependency issue when I hit `bundle install`:

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    pwb was resolved to 0.0.2, which depends on
      activemodel-serializers-xml was resolved to 1.0.1, which depends on
        activerecord (> 5.x)

    pwb was resolved to 0.0.2, which depends on
      globalize-accessors was resolved to 0.1.0, which depends on
        globalize3 (~> 0.3.0) was resolved to 0.3.0, which depends on
          activerecord (>= 3.0.0)

    pwb was resolved to 0.0.2, which depends on
      globalize-accessors was resolved to 0.1.0, which depends on
        globalize3 (~> 0.3.0) was resolved to 0.3.0, which depends on
          paper_trail (~> 2) was resolved to 2.6.3, which depends on
            activerecord (~> 3.0)

    rails (~> 5.0.2) was resolved to 5.0.2, which depends on
      activerecord (= 5.0.2)
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.0.2)

    pwb was resolved to 0.0.2, which depends on
      jsonapi-resources (= 0.8.1) was resolved to 0.8.1, which depends on
        rails (>= 4.0)

    pwb was resolved to 0.0.2, which depends on
      globalize-accessors was resolved to 0.1.0, which depends on
        globalize3 (~> 0.3.0) was resolved to 0.3.0, which depends on
          paper_trail (~> 2) was resolved to 2.0.0, which depends on
            rails (~> 3)

    pwb was resolved to 0.0.2, which depends on
      rails (>= 5.0.0.1, ~> 5.0.0)
```

I'm using ruby 2.4.0

Let me know if you can help me with this issue

Thanks

**Comment by etewiah** [comment]
Hey @cvillalba, thanks for trying it out.

I am guessing that you created a new rails project and added pwb as a gem to that project.

If that is the case can you try adding the globalize gem to your rails project by adding this line to your gemfile:

gem 'globalize', git: 'https://github.com/globalize/globalize'

**Comment by cvillalba** [comment]
@etewiah it was exactly what I needed.

I have one more question though. Once I deploy locally (using `rails server`) I don't see the application in localhost:3000

Thanks, cheers.

**Comment by etewiah** [comment]
@cvillalba glad it is working.

To see the app when you browse to the root you will have to mount it in your routes.rb file like so:
  mount Pwb::Engine => '/'

I will update the documentation.

BTW, are you a native Spanish speaker?  I want to have the documentation available in different languages so I would appreciate some help in keeping this document updated in Spanish:

https://github.com/etewiah/property_web_builder/blob/master/README_es.md

**Comment by etewiah** [comment]
Also, you can install migrations etc with these commands:


rails pwb:install:migrations
rails db:create
rails db:migrate
rails pwb:db:seed

**Comment by cvillalba** [comment]
Hey 

About the documentation, yes I'm native Spanish speaker and I happy to help with the translation. I'll send a PR as soon as I can.

Sorry to bother you again, but I'm getting an error when I run `rails db:migrate`:
`NoMethodError: undefined method `configure' for MoneyRails:Module`

I'm really new in ruby on rails, so sorry about all the questions.

Cheers

**Comment by etewiah** [comment]
No worries - it seems an older version of MoneyRails is used if you have it installed.  I have fixed this by specifying the minimum version of MoneyRails needed in the engine's gemspec.

Update to the fixed version by running  "bundle update pwb" and try again.

Also, make sure you are using postgres as your database - I just now updated the readme with that.

If you come across any other issues, please open a new issue so I can track it separately.

Cheers,

Ed

**Comment by cvillalba** [comment]
Thanks 

That fixed it, but I had another problema that i'll report in other issue.

btw already started with the spanish update in a branch that I just create.

thanks again

**Comment by etewiah** [comment]
Great - looking forward to the Spanish translation ;)
