### ISSUE TITLE
Change Admin Password

### ISSUE THREAD

**Issue by deepcell** [etewiah/property_web_builder#83]
Hi, how can I change admin password?
the table structure has a column called encrypted_password data type character varying, what is the correct way to generate this password? I can do myself, I just need to know which algorithm was used and where it is located or if there exist another way to do that..
Thanks, by the way, very nice App. If I can contribute somehow I will.

**Comment by deepcell** [comment]
Please close this issue. I figured out how to do it. Thanks.

**Comment by dlogiudice1** [comment]
Hello @deepcell , may you share how you changed the default password?,  embarrassingly as it may sound, i was not able to find a way my self.
May you post how to do it?
thank you.

**Comment by raulperezalejo** [comment]
I was able via the console, and worked

**Comment by dlogiudice1** [comment]
thank you Raul, may you share what commands you issued to do it?

**Comment by deepcell** [comment]
The easiest way to do it -> https://DOMAIN.TLD/en/users/edit
