### ISSUE TITLE
Dum, but needed: how to change the admin password

### ISSUE THREAD

**Issue by dlogiudice1** [etewiah/property_web_builder#86]
Hello @etewiah, sorry if this has been asked before, but i sincerely was not able to find any post after searching for a while...
the question is how do I change the default admin password?
thank you and sorry to bother if this has been answered before.

**Comment by etewiah** [comment]
Hello there,
From the console you can run:

```
user = User.where(email: 'admin@example.com').first
user.password = "newpwd"
user.save!
```

You can also browse to "/en/users/edit" and change it there.  (Please don't change it on the demo site at https://propertywebbuilder.herokuapp.com/en )
