### ISSUE TITLE
Property Labels

### ISSUE THREAD

**Issue by rduetsch** [etewiah/property_web_builder#88]
Hello i am a big fan of Property Web Builder.
At the moment i have 3 Problems 

1. How i can use the Property Labels 

2. How i can change the users email Adress

3. How can i speed up the application to open faster

I will appreciate your help

**Comment by etewiah** [comment]
Hi @rduetsch , thanks for your interest in PWB.  Apologies for the delay in replying.  A bit busy right now but will do my best to reply later today or tomorrow.

**Comment by etewiah** [comment]
Okay, finally I got a bit of time.  

How i can use the Property Labels
-  Think of the labels as tags for the properties

How i can change the users email Address
- From the console run:
```
user = User.where(email: 'admin@example.com').first
user.email = "new@another.com"
user.save!
```

How can i speed up the application to open faster
- On the free heroku plan applications take some time to load.  If you upgrade to a paid plan it will load faster.
