### ISSUE TITLE
Import data from csv not working

### ISSUE THREAD

**Issue by moonbrandy** [etewiah/property_web_builder#89]
Import data from csv not working

### Steps to reproduce the issue: download the csv from property list page and upload it from import data from csv page, error message, file invalid.

**Comment by etewiah** [comment]
Hi @moonbrandy , I'm currently a bit busy with some client work but as soon as I get the chance I will have a look at fixing thing.

**Comment by etewiah** [comment]
Sorry but I don't expect to be able to fix this - I don't think this feature is used much anyway.
