### ISSUE TITLE
Rookie user question - Is it possible to edit the layout of the pages / links

### ISSUE THREAD

**Issue by compuhension** [etewiah/property_web_builder#90]
I love the simplicity and elegance of the property.

I am trying to migrate from an old open-realty site, and have everything figured out, except for adding some site links that the client likes to have on the site.

Is it possible to simply add a side navigation, or a custom page with corresponding nav at the top that I could put the links on?

Thanks in advance, and congrats on a great, easy to deploy , product.

**Comment by etewiah** [comment]
Hi @compuhension , thanks for your interest in PWB.  You can add extra links / navigation directly in the code.  
This is the layout that is used by the default theme:

https://github.com/etewiah/property_web_builder/blob/master/app/themes/default/views/layouts/pwb/application.html.erb

You will need to know a bit about html and ruby on rails to do that though.  

In the next version of PWB I hope to be able to add functionality for adding an extra side navigation.
