### ISSUE TITLE
Cant start app

### ISSUE THREAD

**Issue by Viniciusvalenca** [etewiah/property_web_builder#96]
hello people, when i try to run rails s after bundle install i got this message
"The git source https://github.com/fredngo/paloma.git is not yet checked out. Please run `bundle install` before trying to start your application"
anyone know how to solve this ? thanks

**Comment by etewiah** [comment]
Hi, did you follow the instructions here?

https://github.com/etewiah/property_web_builder/wiki/Non-Heroku-Installation

You need to add this to your gemfile:

gem 'paloma', github: 'fredngo/paloma'

**Comment by Viniciusvalenca** [comment]
yeah...i read that, but even with this line on gemfile i still get this error

**Comment by architekco** [comment]
did you npm install? i had this issue as well but was able to move past it (i think the solution was npm install). about to submit the issue i am having.

**Comment by Viniciusvalenca** [comment]
No luck....
`npm WARN saveError ENOENT: no such file or directory, open '/home/vinicius/property_web_builder-master/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/vinicius/property_web_builder-master/package.json'
npm WARN property_web_builder-master No description
npm WARN property_web_builder-master No repository field.
npm WARN property_web_builder-master No README data
npm WARN property_web_builder-master No license field.

up to date in 1.099s
found 0 vulnerabilities`

**Comment by etewiah** [comment]
Can you share your Gemfile and Gemfile.lock files?
