### ISSUE TITLE
Customize admin views

### ISSUE THREAD

**Issue by adrianschung** [etewiah/property_web_builder#99]
Hi, I'm trying to add a tab to the properties form but the admin views are built with Vue and uneditable from the gem. I looked at the new admin repo in #49 but it seems to be incomplete. I was wondering if there was a Vue project for the current admin views that could be used to edit and build new ones?

**Comment by etewiah** [comment]
HI @adrianschung, apologies for the delay in replying.  I've been quite busy.

Right now the source code for the admin view is not available.  I'm doing a complete rewrite for paying clients.  I hope to be able to release that as open source later but for now I'm only able to share it with the small group that is actively helping me work on the new version.
